# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Circle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Circle
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'Alamofire'
  pod 'Moya-ModelMapper/RxSwift'
  
  pod 'Eureka'
  pod 'RxEureka'
  target 'CircleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CircleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
